name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: Run a command with a secret
      env:
        MY_SECRET: ${{ env.SLACK_WEBHOOK_TEST_CHANNEL }}
      run: |
        echo "The secret is $MY_SECRET"
