name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: Run a command with a secret
      env:
        MY_SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo "The secret is $MY_SECRET"
